apiVersion: v1
kind: Pod
metadata:
  name: Pod
  labels:
    name: Pod
spec:
  containers:
  - name: Pod
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
